# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_app', '0002_auto_20160822_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_started', models.DateTimeField()),
                ('procesing_ended', models.DateTimeField()),
                ('recent_processing', models.TextField()),
            ],
        ),
    ]
