# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_app', '0004_auto_20160829_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processortracker',
            name='recent_processing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
