# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_app', '0006_printtitledev_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processortracker',
            name='procesing_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processortracker',
            name='processing_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
